server:
  port: ":8080"
mysql:
  dsn: "root:wanghaoran666@tcp(localhost:3306)/whr_im?charset=utf8mb4&parseTime=True&loc=Local"
objectStorage:
  endpoint: "121.41.66.206:9000"
  accessKey: "minioadmin"
  secretKey: "minioadmin123"
  bucket: "whr-im"
  useSSL: false
  publicBaseUrl: "http://121.41.66.206:9000/whr-im"
