server:
  port: ":8080"
mysql:
  dsn: "mysql-dsn-from-env-or-local-config"
objectStorage:
  endpoint: "minio-endpoint-from-env-or-local-config"
  accessKey: "minio-access-key-from-env-or-local-config"
  secretKey: "minio-secret-key-from-env-or-local-config"
  bucket: "whr-im"
  useSSL: false
  publicBaseUrl: "http://minio.example.com/whr-im"
